# Generated by Django 3.1.5 on 2021-06-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('removals', '0003_auto_20210528_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
